name: Deploy Web Saya

on:
  push:
    branches: ["main"] # Menjalankan asisten setiap kamu update file

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil File
        uses: actions/checkout@v4

      - name: Siapkan Server
        uses: actions/configure-pages@v4

      - name: Upload File ke Server
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Mengambil semua file di folder ini

      - name: Tayangkan Website
        uses: actions/deploy-pages@v4
